feat: professor link table to efficiently store links
NIAEFEUP/tts-be pull request #110
Opened 2024-09-15 22:18 UTC by tomaspalma

Closes #103

2024-09-20 09:21 UTC, Process-ing requested changes

2024-09-20 09:21 UTC, Process-ing commented on postgres/sql/00_schema_postgres.sql
> +    ADD CONSTRAINT "slot_professor_pkey" PRIMARY KEY ("slot_id", "professor_id", "link_id");
Why is `link_id` part of the primary key of `slot_professor` and why is it not a foreign key?

2024-09-20 09:31 UTC, tomaspalma commented on postgres/sql/00_schema_postgres.sql
> +    ADD CONSTRAINT "slot_professor_pkey" PRIMARY KEY ("slot_id", "professor_id", "link_id");
You are right, it doesn't need to be part of the primary key, although it doesn't do any harm.

I already changed it and added it as a foreign key.

2024-09-24 21:02 UTC, Process-ing approved these changes

2024-12-13 10:49 UTC, thePeras commented
Why this isn't merged?

2026-05-13 08:59 UTC, closed without merging